### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by Jeremy5909** [rameshvarun/Azathoth#2]
I don't see a **.exe**, is there a different way? Thanks

**Comment by rameshvarun** [comment]
I don't think there's much value in this repo anymore - all of the interesting Non-Euclidean stuff is in the [other repo](https://github.com/rameshvarun/Dygra).

There is nothing special about the editor itself - you can basically place shapes and add some basic attributes. The editor then saves the level as an XML file. You can even check out the [level XMLs](https://github.com/rameshvarun/Dygra/blob/master/Game/Content/level1.xml) - they are very simple. If I was doing this project in 2020, I would try to find some way to export levels directly from Blender.

If you really want to run it, you might be able to run it using Python2 after installing it + the listed dependencies.
